[project]
name = ""
version = ""
description = ""
authors = [
    {name = "viniihds", email = "viniciushsilva2210@gmail.com"},
]
dependencies = [
    "django>=4.2.4",
    "djangorestframework>=3.14.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

