# Generated by Django 4.2.4 on 2023-09-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiberblu", "0003_itenscompra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="codigo",
        ),
        migrations.AlterField(
            model_name="pedido",
            name="data",
            field=models.DateField(max_length=10),
        ),
    ]
