# Generated by Django 4.2.4 on 2023-08-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiberblu', '0003_grupoproduto_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18)),
                ('endereco', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=14)),
                ('inscricao_estadual', models.CharField(max_length=9)),
                ('classificacao_fiscal', models.CharField(max_length=8)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='fiberblu.categoriaempresa')),
            ],
        ),
    ]
