# Generated by Django 4.2.4 on 2023-09-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiberblu", "0004_remove_produto_codigo_alter_pedido_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
    ]
