# Generated by Django 4.2.4 on 2023-08-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiberblu', '0004_categoriaempresa_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18)),
                ('email', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
    ]
