# Generated by Django 4.2.4 on 2023-08-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiberblu', '0005_representante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.CharField(max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='fiberblu.empresa')),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='fiberblu.produto')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='fiberblu.representante')),
            ],
        ),
    ]
