# Generated by Django 4.2.4 on 2023-09-26 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("fiberblu", "0006_rename_nome_pagamento_descricao_pedido_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="dataPagamento",
            field=models.DateField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
