# Generated by Django 4.2.4 on 2023-09-27 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fiberblu", "0007_pedido_datapagamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itenscompra",
            name="compra",
        ),
        migrations.RemoveField(
            model_name="itenscompra",
            name="produto",
        ),
        migrations.DeleteModel(
            name="Compra",
        ),
        migrations.DeleteModel(
            name="ItensCompra",
        ),
    ]
