# Generated by Django 4.2.4 on 2023-08-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiberblu', '0007_remove_pedido_produtos_pedido_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='volume',
            field=models.IntegerField(max_length=5),
        ),
    ]
