# Generated by Django 4.2.4 on 2023-09-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fiberblu", "0009_pedido_status_pedido_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="representante",
        ),
        migrations.CreateModel(
            name="ItensPedido",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantidade", models.IntegerField(default=1)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="fiberblu.pedido"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="fiberblu.produto"
                    ),
                ),
            ],
        ),
    ]
