# Generated by Django 4.2.6 on 2023-10-10 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fiberblu", "0010_remove_pedido_representante_itenspedido"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="produtos",
        ),
    ]
